spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
rabbitmq:
  port: 5672
  username: WeatherService
  vhost: weather
  queueName: weather_queue
  exchangeName: weather_exchange
  routingKey: weather